export interface JourneyStep {
  id: number;
  name: string;
  nameKo: string;
  description: string;
  descriptionKo: string;
  duration: string;
  durationKo: string;
  documents: string[];
  documentsKo: string[];
  costs: string;
  costsKo: string;
  tips: string[];
  tipsKo: string[];
  stakeholders: string[];
}

export const journeySteps: JourneyStep[] = [
  {
    id: 1,
    name: "Financial Readiness Check",
    nameKo: "재정 준비 상태 확인",
    description: "Check your credit score, savings, monthly debts, and calculate how much home you can afford.",
    descriptionKo: "신용점수, 저축, 월 부채를 확인하고 감당 가능한 매물 가격대를 계산합니다.",
    duration: "~1 week",
    durationKo: "약 1주",
    documents: ["Bank statements (2-3 months)", "Credit report", "List of monthly debts"],
    documentsKo: ["은행 잔고 증명 (2-3개월)", "신용 리포트", "월 부채 목록"],
    costs: "Free (credit report from annualcreditreport.com)",
    costsKo: "무료 (annualcreditreport.com에서 신용 리포트)",
    tips: [
      "Don't open new credit cards or take on new debt",
      "Start saving for down payment + closing costs (2-5% of purchase price)",
      "Check if you qualify as a first-time buyer",
    ],
    tipsKo: [
      "새 신용카드 개설이나 새 부채를 지지 마세요",
      "다운페이먼트 + 클로징 비용 (매매가의 2-5%) 저축 시작",
      "First-time buyer 자격 여부 확인하세요",
    ],
    stakeholders: [],
  },
  {
    id: 2,
    name: "Get Pre-Approved",
    nameKo: "사전 승인(Pre-Approval) 받기",
    description: "A mortgage broker reviews your finances and issues a pre-approval letter showing how much you can borrow.",
    descriptionKo: "모기지 브로커가 재정 상태를 검토하고, 대출 가능 금액을 보여주는 사전 승인서를 발급합니다.",
    duration: "~2 weeks",
    durationKo: "약 2주",
    documents: ["W-2 (2 years)", "Tax returns (2 years)", "Bank statements", "Employment verification letter"],
    documentsKo: ["W-2 (2년)", "세금 신고서 (2년)", "은행 잔고 증명", "고용 확인서"],
    costs: "Free",
    costsKo: "무료",
    tips: [
      "Compare at least 2-3 mortgage brokers",
      "Ask if they check DTI thoroughly upfront — this prevents rejection later",
      "If you have overseas property, disclose it NOW, not later",
    ],
    tipsKo: [
      "최소 2-3곳의 모기지 브로커를 비교하세요",
      "초기에 DTI를 철저히 검토하는지 확인하세요 — 나중에 거절 방지",
      "해외 부동산이 있으면 지금 바로 공개하세요, 나중이 아니라",
    ],
    stakeholders: ["Mortgage Broker"],
  },
  {
    id: 3,
    name: "Choose a Buyer's Agent",
    nameKo: "바이어 에이전트 선정",
    description: "Find a real estate agent who represents YOUR interests. Sign an exclusive buyer representation agreement.",
    descriptionKo: "당신의 이익을 대변하는 부동산 에이전트를 찾고, 바이어 대리 계약서에 서명합니다.",
    duration: "~1 week",
    durationKo: "약 1주",
    documents: ["Exclusive Buyer Representation Agreement"],
    documentsKo: ["바이어 독점 대리 계약서"],
    costs: "Agent commission: typically 2-3% (negotiable, paid at closing)",
    costsKo: "에이전트 커미션: 보통 2-3% (협상 가능, 클로징 시 지불)",
    tips: [
      "Since 2024 NAR settlement, buyer agent agreements are mandatory",
      "Check the 'exclusive' period and commission structure carefully",
      "Choose someone who knows your target neighborhood well",
    ],
    tipsKo: [
      "2024년 NAR 합의 이후 바이어 에이전트 계약 의무화",
      "'독점' 기간과 커미션 구조를 꼼꼼히 확인하세요",
      "타겟 지역을 잘 아는 에이전트를 선택하세요",
    ],
    stakeholders: ["Buyer's Agent"],
  },
  {
    id: 4,
    name: "Search & Make an Offer",
    nameKo: "매물 탐색 + 오퍼",
    description: "View properties, compare options, and submit an offer on your chosen home.",
    descriptionKo: "매물을 보고, 비교하고, 선택한 집에 오퍼를 제출합니다.",
    duration: "2-6 weeks",
    durationKo: "2-6주",
    documents: ["Pre-approval letter (to include with offer)", "Offer letter"],
    documentsKo: ["사전 승인서 (오퍼에 첨부)", "오퍼 레터"],
    costs: "Free (but budget time for multiple viewings)",
    costsKo: "무료 (하지만 여러 번 방문할 시간 필요)",
    tips: [
      "Don't fall in love with one property too early",
      "Research comparable sales in the area",
      "Your offer strategy depends on market conditions (seller's vs buyer's market)",
    ],
    tipsKo: [
      "한 매물에 너무 일찍 빠지지 마세요",
      "해당 지역의 비교 매매 사례를 조사하세요",
      "오퍼 전략은 시장 상황(셀러 마켓 vs 바이어 마켓)에 따라 달라집니다",
    ],
    stakeholders: ["Buyer's Agent", "Seller's Agent"],
  },
  {
    id: 5,
    name: "Contract of Sale + Attorney Review",
    nameKo: "매매 계약서 + 변호사 리뷰",
    description: "Once your offer is accepted, both attorneys negotiate the Contract of Sale. In NY, an attorney is required.",
    descriptionKo: "오퍼가 수락되면 양측 변호사가 매매 계약서를 협상합니다. NY에서는 변호사가 필수입니다.",
    duration: "1-2 weeks",
    durationKo: "1-2주",
    documents: ["Contract of Sale", "Rider", "Amendment (if any)"],
    documentsKo: ["매매 계약서", "Rider (부속 조항)", "수정안 (있는 경우)"],
    costs: "Attorney fee: $2,000-$4,000",
    costsKo: "변호사 비용: $2,000-$4,000",
    tips: [
      "Pay attention to escrow conditions — when you can and can't get it back",
      "Check all contingency deadlines (inspection, financing, appraisal)",
      "Understand the difference between Contract of Sale, Rider, and Amendment",
    ],
    tipsKo: [
      "에스크로 조건에 주의하세요 — 언제 돌려받을 수 있고 없는지",
      "모든 컨틴전시 마감일 확인 (인스펙션, 파이낸싱, 감정평가)",
      "매매 계약서, Rider, Amendment의 차이를 이해하세요",
    ],
    stakeholders: ["Attorney", "Seller's Attorney"],
  },
  {
    id: 6,
    name: "Inspection + Negotiation",
    nameKo: "인스펙션 + 협상",
    description: "A professional inspector examines the property. Based on findings, you may negotiate repairs or credits.",
    descriptionKo: "전문 검사관이 매물을 검사합니다. 결과에 따라 수리나 크레딧을 협상할 수 있습니다.",
    duration: "~1 week",
    durationKo: "약 1주",
    documents: ["Inspection report"],
    documentsKo: ["인스펙션 리포트"],
    costs: "Inspection fee: $400-$800",
    costsKo: "인스펙션 비용: $400-$800",
    tips: [
      "Attend the inspection in person if possible",
      "Seller credits vs price reduction vs repair requests — each has pros/cons",
      "Know the seller credit limits for your loan program (typically 3-6%)",
    ],
    tipsKo: [
      "가능하면 인스펙션에 직접 참석하세요",
      "셀러 크레딧 vs 가격 인하 vs 수리 요청 — 각각 장단점이 있습니다",
      "대출 프로그램별 셀러 크레딧 한도를 알아두세요 (보통 3-6%)",
    ],
    stakeholders: ["Inspector", "Buyer's Agent", "Seller's Agent", "Attorney"],
  },
  {
    id: 7,
    name: "Mortgage Application + Underwriting",
    nameKo: "모기지 신청 + 심사(Underwriting)",
    description: "Submit your full mortgage application. The underwriter verifies everything — this is the most critical step.",
    descriptionKo: "모기지 본 신청서를 제출합니다. 언더라이터가 모든 것을 검증합니다 — 가장 중요한 단계입니다.",
    duration: "2-3 weeks",
    durationKo: "2-3주",
    documents: ["1003 Loan Application", "Updated bank statements", "Employment verification", "All previously submitted docs"],
    documentsKo: ["1003 대출 신청서", "최신 은행 잔고 증명", "고용 확인서", "이전 제출 서류 전체"],
    costs: "Application fee varies by lender",
    costsKo: "신청 수수료는 은행마다 다름",
    tips: [
      "DO NOT change jobs, open new accounts, or make large purchases during this period",
      "Respond to underwriter requests within 24 hours",
      "If denied, you can try a different lender — don't give up",
    ],
    tipsKo: [
      "이 기간 동안 이직, 새 계좌 개설, 큰 구매를 하지 마세요",
      "언더라이터 요청에 24시간 내 응답하세요",
      "거절되면 다른 은행으로 시도할 수 있습니다 — 포기하지 마세요",
    ],
    stakeholders: ["Mortgage Broker", "Underwriter"],
  },
  {
    id: 8,
    name: "Appraisal",
    nameKo: "감정평가(Appraisal)",
    description: "The lender orders an independent appraisal to confirm the property's value matches the purchase price.",
    descriptionKo: "대출 기관이 독립 감정평가를 실시해 매물 가치가 매매가와 일치하는지 확인합니다.",
    duration: "1-2 weeks",
    durationKo: "1-2주",
    documents: ["Appraisal report (ordered by lender)"],
    documentsKo: ["감정평가 보고서 (대출 기관이 주문)"],
    costs: "Appraisal fee: $500-$1,000",
    costsKo: "감정평가 비용: $500-$1,000",
    tips: [
      "If appraisal comes in low, you have options: renegotiate, cover the gap, or walk away",
      "An appraisal gap means the bank won't lend the full amount",
      "Your agent can provide comparable sales data to support the value",
    ],
    tipsKo: [
      "감정가가 낮으면 선택지가 있습니다: 재협상, 차액 보충, 또는 계약 해지",
      "Appraisal Gap은 은행이 전액을 대출하지 않는다는 뜻",
      "에이전트가 비교 매매 데이터를 제공해 가치를 뒷받침할 수 있습니다",
    ],
    stakeholders: ["Appraiser", "Mortgage Broker"],
  },
  {
    id: 9,
    name: "Board Application",
    nameKo: "보드 어플리케이션 (콘도/코압)",
    description: "For condos and co-ops, submit a board application package. Co-ops typically require an interview.",
    descriptionKo: "콘도나 코압의 경우 보드 어플리케이션 패키지를 제출합니다. 코압은 보통 인터뷰가 필요합니다.",
    duration: "2-4 weeks",
    durationKo: "2-4주",
    documents: ["Board application form", "Financial statements", "Reference letters (10+)", "Employment verification"],
    documentsKo: ["보드 어플리케이션 양식", "재정 서류", "추천서 (10통+)", "고용 확인서"],
    costs: "Application fee: $500-$1,000",
    costsKo: "신청 수수료: $500-$1,000",
    tips: [
      "Start collecting reference letters early — you'll need 10+",
      "Condo boards typically approve, co-op boards can reject without reason",
      "Digital platforms like Domicile make submission easier",
    ],
    tipsKo: [
      "추천서를 일찍 모으기 시작하세요 — 10통 이상 필요",
      "콘도 보드는 보통 승인하지만, 코압 보드는 이유 없이 거절 가능",
      "Domicile 같은 디지털 플랫폼으로 제출이 쉬워집니다",
    ],
    stakeholders: ["Board Members", "Management Company"],
  },
  {
    id: 10,
    name: "Title Search + Insurance",
    nameKo: "타이틀 검색 + 보험",
    description: "A title company searches for any liens, judgments, or claims on the property. You'll also get condo insurance.",
    descriptionKo: "타이틀 회사가 매물에 대한 유치권, 판결, 청구를 검색합니다. 콘도 보험도 가입합니다.",
    duration: "1-2 weeks",
    durationKo: "1-2주",
    documents: ["Title report", "Title insurance policy", "Condo/homeowner's insurance"],
    documentsKo: ["타이틀 리포트", "타이틀 보험", "콘도/주택 소유자 보험"],
    costs: "Title insurance: $1,000-$3,000 | Condo insurance: $500-$1,500/year",
    costsKo: "타이틀 보험: $1,000-$3,000 | 콘도 보험: $500-$1,500/년",
    tips: [
      "Title issues are rare but can delay closing significantly",
      "Lender's title insurance is required, owner's is optional but recommended",
      "Get condo insurance quotes from multiple providers",
    ],
    tipsKo: [
      "타이틀 이슈는 드물지만 클로징을 크게 지연시킬 수 있습니다",
      "대출 기관 타이틀 보험은 필수, 소유자 보험은 선택이지만 권장",
      "콘도 보험 견적을 여러 곳에서 받으세요",
    ],
    stakeholders: ["Title Company", "Insurance Agent"],
  },
  {
    id: 11,
    name: "Closing",
    nameKo: "클로징",
    description: "Sign all final documents, wire the remaining funds, and receive the keys to your new home.",
    descriptionKo: "최종 서류에 서명하고, 잔금을 송금하고, 새 집 열쇠를 받습니다.",
    duration: "1 day",
    durationKo: "1일",
    documents: ["Closing Disclosure (CD)", "Loan contract", "Wire transfer confirmation"],
    documentsKo: ["Closing Disclosure (CD)", "대출 계약서", "송금 확인서"],
    costs: "Closing costs: 2-5% of purchase price (total)",
    costsKo: "클로징 비용: 매매가의 2-5% (전체)",
    tips: [
      "VERIFY wire transfer instructions by PHONE — email-only instructions could be fraud",
      "Review the Closing Disclosure 3 days before closing",
      "Bring government-issued photo ID",
    ],
    tipsKo: [
      "송금 지시를 반드시 전화로 확인하세요 — 이메일만 믿으면 사기 위험",
      "Closing Disclosure를 클로징 3일 전에 검토하세요",
      "정부 발행 사진 신분증을 가져가세요",
    ],
    stakeholders: ["Attorney", "Title Company", "Mortgage Broker"],
  },
  {
    id: 12,
    name: "Move In!",
    nameKo: "입주!",
    description: "Congratulations! You're a homeowner. Set up utilities, change your address, and enjoy your new home.",
    descriptionKo: "축하합니다! 집주인이 되었습니다. 유틸리티 설정, 주소 변경, 새 집을 즐기세요.",
    duration: "Ongoing",
    durationKo: "진행 중",
    documents: ["Move-in checklist", "Utility setup confirmations"],
    documentsKo: ["입주 체크리스트", "유틸리티 설정 확인서"],
    costs: "Moving costs, initial furnishing",
    costsKo: "이사 비용, 초기 가구 구입",
    tips: [
      "File for your homestead exemption if applicable",
      "Keep all closing documents in a safe place",
      "Set up automatic mortgage payments",
    ],
    tipsKo: [
      "해당되는 경우 Homestead Exemption을 신청하세요",
      "모든 클로징 서류를 안전한 곳에 보관하세요",
      "모기지 자동 납부를 설정하세요",
    ],
    stakeholders: [],
  },
];
